# Generated by Django 3.2.1 on 2021-05-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='powertrain',
            new_name='engine',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='max_passenger',
            new_name='seating_capacity',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='manufacturing_year',
            new_name='year',
        ),
    ]
